### ISSUE TITLE
Color info card UI development

### ISSUE THREAD

**Issue by harundogdu** [yusufalperendumlu/color-palette#15]
![image](https://user-images.githubusercontent.com/43449361/224831859-cd13496a-b9df-4700-aa76-565abffa699e.png)

- Burada bir UI sorunu var. Okuma zor oluyor. Bu konuda tasarımsal bir aksiyon alalım. (Background filter / backdrop filter: blur)

**Comment by yusufalperendumlu** [comment]
![Screenshot_15](https://user-images.githubusercontent.com/101521433/225138022-10d44758-9a5a-469b-ab46-42d9ddb40563.png)

@harundogdu 
What do you think about the new design ? (use to Background filter / backdrop filter: blur)

**Comment by harundogdu** [comment]
Can you add an opacity value for the background too? 

Example CSS = opacity: 0.8 , backdrop-filter: 5px

**Comment by yusufalperendumlu** [comment]
![Screenshot_16](https://user-images.githubusercontent.com/101521433/225147306-9fe5601a-9972-4c78-b7f6-5455eeb97ce5.png)

@harundogdu 

Thank you for the suggestions. How did you find it now?

**Comment by harundogdu** [comment]
Nice! You can open PR.
